#!/usr/bin/env bash
# COnfigure ngnix to redirect to another page
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com/hoodieslover/status/1290095896059764737?s=19 permanent;' /etc/nginx/sites-available/default
sudo nginx -t
sudo service nginx restart

