#!/usr/bin/env bash
# Set up NGINX server with custom http header
sudo apt-get update
sudo apt-get -y install nginx
header="\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "31i\ $header" /etc/nginx/sites-enabled/default
sudo service nginx reload
sudo service nginx restart

