#!/usr/bin/env bash
# scritp that sets up the load balancer
sudo apt -y update

sudo apt -y install software-properties-common
sudo apt-add-repository -y ppa:vbernat/haproxy-1.8

sudo apt -y update
sudo apt -y install haproxy=1.8\*

sudo sed -i "s/ENABLED=0/ENABLED=1/g" /etc/default/haproxy

sudo echo "listen 1489-lb-01" >> /etc/haproxy/haproxy.cfg
sudo echo "	bind 0:80" >> /etc/haproxy/haproxy.cfg
sudo echo "	mode http" >> /etc/haproxy/haproxy.cfg
sudo echo "	stats enable" >> /etc/haproxy/haproxy.cfg
sudo echo "	balance roundrobin" >> /etc/haproxy/haproxy.cfg
sudo echo "	option httpclose" >> /etc/haproxy/haproxy.cfg
sudo echo "	option forwardfor" >> /etc/haproxy/haproxy.cfg
sudo echo "	server 1489-web-01 34.74.9.37 check port 80" >> /etc/haproxy/haproxy.cfg
sudo echo "	server 1489-web-02 34.74.166.225 check port 80" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
