#!/usr/bin/env bash
#script that displays numbers from 1 to 100.
for counter in {1..100}
do
	if [ $((counter % 15)) == 0 ] 
	then
		echo "FizzBuzz"
	elif [ $((counter % 3)) == 0 ]
	then
		echo "Fizz"
	elif [ $((counter % 5)) == 0 ]
	then 
		echo "Buzz"
	else
		echo $counter
	fi
	((counter++))
done
