#!/usr/bin/env bash
# executes nginx service as nginx user
chmod 007 /etc/nginx/nginx.conf
pkill apache2
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
chmod 000 /etc/nginx/nginx.conf
